##############################################################################
# DATABASE CONFIGURATION DATA
[database]

connection_string = "root:bersen@/funcom"
max_idle_connections = 5
max_open_connections = 20
connection_max_lifetime = "60s"
driver_name = "mysql"

###############################################################################
# HTTP server configuration

[http]

http_addr = ":4000"

[https]

https_addr = ":443"
###############################################################################

